import type { User, Question, Exam } from "./types"

export const seedUsers: User[] = [
  {
    id: "u1",
    name: "Admin User",
    email: "admin@exam.com",
    password: "admin123",
    role: "admin",
    createdAt: "2025-01-15T10:00:00Z",
  },
  {
    id: "u2",
    name: "Alice Johnson",
    email: "alice@exam.com",
    password: "student123",
    role: "student",
    createdAt: "2025-02-01T09:00:00Z",
  },
  {
    id: "u3",
    name: "Bob Smith",
    email: "bob@exam.com",
    password: "student123",
    role: "student",
    createdAt: "2025-02-05T14:00:00Z",
  },
]

export const seedQuestions: Question[] = [
  // Mathematics - Easy
  {
    id: "q1",
    text: "What is the value of 15 + 27?",
    options: ["32", "42", "52", "40"],
    correctAnswer: 1,
    subject: "Mathematics",
    difficulty: "easy",
    createdBy: "u1",
  },
  {
    id: "q2",
    text: "What is 8 x 7?",
    options: ["54", "48", "56", "64"],
    correctAnswer: 2,
    subject: "Mathematics",
    difficulty: "easy",
    createdBy: "u1",
  },
  {
    id: "q3",
    text: "What is 144 / 12?",
    options: ["10", "11", "12", "14"],
    correctAnswer: 2,
    subject: "Mathematics",
    difficulty: "easy",
    createdBy: "u1",
  },
  // Mathematics - Medium
  {
    id: "q4",
    text: "What is the square root of 169?",
    options: ["11", "12", "13", "14"],
    correctAnswer: 2,
    subject: "Mathematics",
    difficulty: "medium",
    createdBy: "u1",
  },
  {
    id: "q5",
    text: "Solve: 3x + 7 = 22. What is x?",
    options: ["3", "4", "5", "6"],
    correctAnswer: 2,
    subject: "Mathematics",
    difficulty: "medium",
    createdBy: "u1",
  },
  {
    id: "q6",
    text: "What is the area of a circle with radius 7? (Use pi = 22/7)",
    options: ["144", "154", "164", "176"],
    correctAnswer: 1,
    subject: "Mathematics",
    difficulty: "medium",
    createdBy: "u1",
  },
  // Mathematics - Hard
  {
    id: "q7",
    text: "What is the derivative of f(x) = 3x^2 + 2x + 1?",
    options: ["6x + 2", "3x + 2", "6x + 1", "6x^2 + 2"],
    correctAnswer: 0,
    subject: "Mathematics",
    difficulty: "hard",
    createdBy: "u1",
  },
  // Science - Easy
  {
    id: "q8",
    text: "What is the chemical symbol for water?",
    options: ["HO", "H2O", "H2O2", "OH"],
    correctAnswer: 1,
    subject: "Science",
    difficulty: "easy",
    createdBy: "u1",
  },
  {
    id: "q9",
    text: "What planet is known as the Red Planet?",
    options: ["Venus", "Jupiter", "Mars", "Saturn"],
    correctAnswer: 2,
    subject: "Science",
    difficulty: "easy",
    createdBy: "u1",
  },
  {
    id: "q10",
    text: "What gas do plants absorb from the atmosphere?",
    options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"],
    correctAnswer: 2,
    subject: "Science",
    difficulty: "easy",
    createdBy: "u1",
  },
  // Science - Medium
  {
    id: "q11",
    text: "What is the powerhouse of the cell?",
    options: ["Nucleus", "Ribosome", "Mitochondria", "Golgi Body"],
    correctAnswer: 2,
    subject: "Science",
    difficulty: "medium",
    createdBy: "u1",
  },
  {
    id: "q12",
    text: "What is the speed of light in vacuum (approximately)?",
    options: [
      "3 x 10^6 m/s",
      "3 x 10^8 m/s",
      "3 x 10^10 m/s",
      "3 x 10^5 m/s",
    ],
    correctAnswer: 1,
    subject: "Science",
    difficulty: "medium",
    createdBy: "u1",
  },
  {
    id: "q13",
    text: "Which element has the atomic number 6?",
    options: ["Nitrogen", "Oxygen", "Carbon", "Boron"],
    correctAnswer: 2,
    subject: "Science",
    difficulty: "medium",
    createdBy: "u1",
  },
  // Science - Hard
  {
    id: "q14",
    text: "What is the Heisenberg Uncertainty Principle about?",
    options: [
      "Energy conservation in quantum systems",
      "Simultaneous measurement of position and momentum",
      "Wave-particle duality of light",
      "Quantization of electron orbits",
    ],
    correctAnswer: 1,
    subject: "Science",
    difficulty: "hard",
    createdBy: "u1",
  },
  // Programming - Easy
  {
    id: "q15",
    text: "Which keyword is used to declare a variable in JavaScript?",
    options: ["var", "int", "string", "dim"],
    correctAnswer: 0,
    subject: "Programming",
    difficulty: "easy",
    createdBy: "u1",
  },
  {
    id: "q16",
    text: "What does HTML stand for?",
    options: [
      "Hyper Text Markup Language",
      "High Tech Modern Language",
      "Hyper Transfer Markup Language",
      "Home Tool Markup Language",
    ],
    correctAnswer: 0,
    subject: "Programming",
    difficulty: "easy",
    createdBy: "u1",
  },
  {
    id: "q17",
    text: "Which symbol is used for single-line comments in JavaScript?",
    options: ["#", "//", "/*", "--"],
    correctAnswer: 1,
    subject: "Programming",
    difficulty: "easy",
    createdBy: "u1",
  },
  // Programming - Medium
  {
    id: "q18",
    text: "What is the time complexity of binary search?",
    options: ["O(n)", "O(log n)", "O(n log n)", "O(1)"],
    correctAnswer: 1,
    subject: "Programming",
    difficulty: "medium",
    createdBy: "u1",
  },
  {
    id: "q19",
    text: "Which data structure uses FIFO (First In, First Out)?",
    options: ["Stack", "Queue", "Tree", "Graph"],
    correctAnswer: 1,
    subject: "Programming",
    difficulty: "medium",
    createdBy: "u1",
  },
  {
    id: "q20",
    text: "What does the 'this' keyword refer to in JavaScript?",
    options: [
      "The current function",
      "The global object always",
      "The object that is executing the current function",
      "The parent function",
    ],
    correctAnswer: 2,
    subject: "Programming",
    difficulty: "medium",
    createdBy: "u1",
  },
  // Programming - Hard
  {
    id: "q21",
    text: "What is a closure in JavaScript?",
    options: [
      "A function that returns another function",
      "A function bundled with its lexical environment",
      "A self-invoking function",
      "A function with no parameters",
    ],
    correctAnswer: 1,
    subject: "Programming",
    difficulty: "hard",
    createdBy: "u1",
  },
  {
    id: "q22",
    text: "Which sorting algorithm has the best average-case time complexity?",
    options: ["Bubble Sort", "Selection Sort", "Merge Sort", "Insertion Sort"],
    correctAnswer: 2,
    subject: "Programming",
    difficulty: "hard",
    createdBy: "u1",
  },
]

export const seedExams: Exam[] = [
  {
    id: "e1",
    title: "Mathematics Fundamentals",
    description:
      "Test your knowledge of basic to intermediate mathematics concepts including arithmetic, algebra, and geometry.",
    subject: "Mathematics",
    duration: 30,
    totalQuestions: 5,
    passingScore: 60,
    status: "active",
    questionIds: ["q1", "q2", "q3", "q4", "q5"],
    createdBy: "u1",
    createdAt: "2025-03-01T10:00:00Z",
    scheduledAt: "2025-03-10T09:00:00Z",
  },
  {
    id: "e2",
    title: "Science General Knowledge",
    description:
      "A comprehensive science exam covering physics, chemistry, and biology fundamentals.",
    subject: "Science",
    duration: 25,
    totalQuestions: 5,
    passingScore: 50,
    status: "active",
    questionIds: ["q8", "q9", "q10", "q11", "q12"],
    createdBy: "u1",
    createdAt: "2025-03-02T11:00:00Z",
    scheduledAt: "2025-03-12T10:00:00Z",
  },
  {
    id: "e3",
    title: "Programming Basics",
    description:
      "Test your understanding of programming concepts, data structures, and algorithms.",
    subject: "Programming",
    duration: 20,
    totalQuestions: 5,
    passingScore: 60,
    status: "draft",
    questionIds: ["q15", "q16", "q17", "q18", "q19"],
    createdBy: "u1",
    createdAt: "2025-03-05T08:00:00Z",
    scheduledAt: "2025-03-20T14:00:00Z",
  },
]
